version: '3'
services:
  app:
    container_name: ptt-observer
    # restart: always
    build: .
    volumes:
      - .:/usr/src/app
    links:
      - mongo
  mongo:
    container_name: ptt-observer-mongo
    image: mongo
    volumes:
      - ./data:/data/db
  mongo-express:
    image: mongo-express
    links:
      - mongo
    ports:
      - 8989:8081
